// <auto-generated />
namespace FilmDatabase.Migrations.FilmContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Initia1l : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initia1l));
        
        string IMigrationMetadata.Id
        {
            get { return "201704220705282_Initia1l"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
